//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SPAEntities : DbContext
    {
        public SPAEntities()
            : base("name=SPAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHINHANH> CHINHANHs { get; set; }
        public virtual DbSet<CHITIET_GIUONG> CHITIET_GIUONG { get; set; }
        public virtual DbSet<CHITIET_LICHHEN> CHITIET_LICHHEN { get; set; }
        public virtual DbSet<DATTRUOC> DATTRUOCs { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<GIOHANG> GIOHANGs { get; set; }
        public virtual DbSet<GIUONG> GIUONGs { get; set; }
        public virtual DbSet<LICHHEN> LICHHENs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<TTCANHAN> TTCANHANs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    
        public virtual ObjectResult<insert_user_Result> insert_user(string name, string pass)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<insert_user_Result>("insert_user", nameParameter, passParameter);
        }
    }
}
